// This file is automatically generated from your CSS. Any edits will be overwritten.
export const chartWrapper: string;
export const chart: string;
export const pathHolder: string;
export const chartLine: string;
export const chartLineHidden: string;
export const chartGridLine: string;
export const chartGridLineEasyOut: string;
export const chartGridText: string;
export const activeLine: string;
export const activeDot: string;
