// This file is automatically generated from your CSS. Any edits will be overwritten.
export const xAxis: string;
export const xAxisWrapper: string;
export const xAxisLabel: string;
export const xAxisLabelDissappear: string;
