// This file is automatically generated from your CSS. Any edits will be overwritten.
export const previewRange: string;
export const previewRangeOverlay: string;
export const previewRangeLeft: string;
export const previewRangeRight: string;
export const previewRangeSelectorLeft: string;
export const previewRangeSelectorRight: string;
export const previewRangeCenter: string;
export const previewRangeChart: string;
export const chartLine: string;
export const chartLineHidden: string;
