// This file is automatically generated from your CSS. Any edits will be overwritten.
export const toolTip: string;
export const toolTipDate: string;
export const toolTipValues: string;
export const valuesBlock: string;
export const valuesBlockNumber: string;
export const valuesBlockName: string;
