// This file is automatically generated from your CSS. Any edits will be overwritten.
export const chips: string;
export const chipsAvailable: string;
export const chipsCheckbox: string;
export const chipsChecked: string;
export const chipsUnChecked: string;
export const chipsCheckMark: string;
export const chipsName: string;
